package pkg;
// Generated Apr 28, 2015 9:12:45 PM by Hibernate Tools 3.6.0



/**
 * Atmlogin2 generated by hbm2java
 */
public class Atmlogin2  implements java.io.Serializable {


     private String uname;
     private String upass;
     private String salt;

    public Atmlogin2() {
    }

    public Atmlogin2(String uname, String upass, String salt) {
       this.uname = uname;
       this.upass = upass;
       this.salt = salt;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getUpass() {
        return this.upass;
    }
    
    public void setUpass(String upass) {
        this.upass = upass;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }




}


